### ISSUE TITLE
Suggest parameter name in "extract value" refactoring

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#13]
In the following expression:

```
print("foo");
```

When I call the extract value refactoring on `"foo"`, it would be cool if the suggested names contained:

- `val` (the parameter name, taken from the signature of `print`)
- possibly the string content (`foo`), if it matches `\w+`

Those would be more meaningful than `string` :)

**Comment by gavinking** [comment]
That would be nice, yes.
