### ISSUE TITLE
Errors in the AST Delta builder

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-common#14]
various tests in the delta builder fail.

**Comment by davidfestal** [comment]
@gavinking : please could you have a look at (and run) this new test about the scoping rules of function parameter arguments (that seem to have changed since the AST Builder was implemented) : 

[InvalidFunctionalParameterScope.ceylon](https://github.com/ceylon/ceylon-ide-common/blob/master/test-source/test/com/redhat/ceylon/ide/common/model/delta/InvalidFunctionalParameterScope.ceylon)

And tell me what you think of the failure : What is really the expected scope now ? 

Then should we open an issue in `ceylon-spec` for this ? or should I adapt my AST Builder code to reflect this scoping change ?

**Comment by gavinking** [comment]
I don't know what you're fussing about here. The scope of the a value declaration (even a parameter of a parameter) is the value declaration itself. That's *completely* normal. Perhaps you're confusing `scope` with `container`?

**Comment by davidfestal** [comment]
Look here : 
https://github.com/ceylon/ceylon-ide-common/blob/b50b742277d5ea62b85d6c753c05097789f3919c/source/com/redhat/ceylon/ide/common/model/delta/deltaBuilder.ceylon#L606

In this code, some months ago before your changes to remove the `NaturalVisitor`, for arguments of Functional parameters, the scope *used to be* the `Function` model object itself. But now, since it isn't anymore, the following `ASTDetaBuilder` tests are now failing : 
- methodEquivalentFunctionalParameter
- methodFunctionalParameterArgumentNameChanged
- methodFunctionalParameterNameChanged

**Comment by gavinking** [comment]
Well that was a bug then.

**Comment by davidfestal** [comment]
OK, let me change the related `deltaBuilder` code then

**Comment by davidfestal** [comment]
All the `ceylon-ide-common` tests pass now. Closing.
