### ISSUE TITLE
incorrect handling of value constructors in completions

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#20]
- Second-level completions, and
- linked mode argument completions

Do not correctly handle value constructors. See below:

<img width="178" alt="screen shot 2015-12-11 at 3 38 24 pm" src="https://cloud.githubusercontent.com/assets/579974/11746295/c01915ee-a01d-11e5-9295-694048ffa314.png">
<img width="271" alt="screen shot 2015-12-11 at 3 38 47 pm" src="https://cloud.githubusercontent.com/assets/579974/11746296/c031d4bc-a01d-11e5-9265-e155c8cfdb87.png">

**Comment by gavinking** [comment]
Note that this bug affects the current 1.2.0 release of the IDE.

@bjansen @davidfestal where does this get fixed now? In the new Ceylon code? In the old Java code? Both?

**Comment by bjansen** [comment]
In the new Ceylon code on master, in the old Java code on 1.2.0-fixes.

**Comment by davidfestal** [comment]
probably both :-)

**Comment by gavinking** [comment]
*sighs*

**Comment by gavinking** [comment]
This is done.
