### ISSUE TITLE
type arguments not shown in hover for generic instantiation

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#22]
I have this code:

    value array = Array { 1, 2 };

Hovering `Array` should show me the inferred type argument but it doesn't.

**Comment by bjansen** [comment]
I fixed a few things but now it's not inferring the type argument everywhere, which is a little odd:

```ceylon
class Array<Integer>({Integer*} elements)
  extends Basic
  satisfies SearchableList<Element> & Ranged<Integer,Element,Array<Element>>
  given Element = Integer
```

I'll keep debugging...
