### ISSUE TITLE
Wrong proposals in incomplete if expression

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#29]
In the following code:

```ceylon
shared actual Image image => if (declaration.<caret here>);
```

the completion proposals contain toplevel declarations instead of members of `declaration`, I suppose it's because the `if` expression is incomplete.

**Comment by gavinking** [comment]
Looks to me like the code is getting parsed correctly, and the right type is assigned to the `BaseMemberExpression`. So this does not appear to be a bug in the typechecker.

**Comment by bjansen** [comment]
I get the correct proposals if the `if` expression is complete, i.e.

```
shared actual Image image => if (declaration.<caret here>) then true else false;
```

This is probably simple to fix.

**Comment by bjansen** [comment]
Actually I have the same kind of problem in function declarations:

```ceylon
    shared actual void newProposal(IdeaQuickFixData data, String desc, Tree.<caret here>)
            => makeAvailable(desc);
```

I expect inner classes of `Tree` to be shown, but instead I see toplevel declarations.

**Comment by bjansen** [comment]
It turns out that when the `if` expression is incomplete, the CompilationUnit's `endIndex` is wrong (it looks like it contains the `endIndex` of the `if` keyword). As a result, `FindNodeVisitor` doesn't work as expected, and the completion manager is told that the current node is the compilation unit.

@gavinking any idea how to fix that?

**Comment by gavinking** [comment]
Look in Ceylon.g.

On Fri, Feb 26, 2016 at 4:06 PM, Bastien Jansen <notifications@github.com>
wrote:

> It turns out that when the if expression is incomplete, the
> CompilationUnit's endIndex is wrong (it looks like it contains the
> endIndex of the if keyword). As a result, FindNodeVisitor doesn't work as
> expected, and the completion manager is told that the current node is the
> compilation unit.
>
> @gavinking <https://github.com/gavinking> any idea how to fix that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-ide-common/issues/29#issuecomment-189316036>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org

**Comment by gavinking** [comment]
Should be fixed now.
