### ISSUE TITLE
Enhance completion results in extends/satisfies

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#31]
9 times out of 10, when I try to complete a class name in an `extends` clause, the class I'm looking for does not appear because it turns out it's an interface, and the completion manager tries to be too smart and restricts results to classes only. 

In this case, it would be nice to also suggest interfaces, then automatically replace `extends` with `satisfies` (or drop the `extends` and add `& MyInterface` to an existing `satisfies` clause).

This would also work with class proposals in `satisfies` clauses.

WDYT?

**Comment by gavinking** [comment]
Rrrrrm. I don't like it.

**Comment by bjansen** [comment]
Then make it configurable. 

IntelliJ's API is so big that I can never remember if what I'm implementing is a class or an interface.

**Comment by gavinking** [comment]
I can think of lots of circumstances where it would be much more unhelpful than helpful. I would not want it to be the default.

**Comment by bjansen** [comment]
What do you have in mind, other than "it will clutter up the list of proposals"?
