### ISSUE TITLE
"Convert to shortcut refinement" shouldn't always be suggested 

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#35]
It looks like the quick assist shouldn't be suggested in such cases:

```ceylon
interface Bar {
    shared formal Foo<A, B, C> foo<A, B, C>();
}
class Cls() satisfies Bar {
    shared actual Nothing foo<A, B, C>() => nothing;
}
```

Otherwise I end up with this error:

```
specification statements may not have type parameters
```

and a side effect:

```
the '' caused an exception visiting a 'TypeParameterList' node: '"java.lang.ClassCastException: com.redhat.ceylon.model.typechecker.model.Value cannot be cast to com.redhat.ceylon.model.typechecker.model.Generic"' at 'com.redhat.ceylon.compiler.typechecker.analyzer.DeclarationVisitor.visit(DeclarationVisitor.java:804)'
```

@gavinking can you confirm this syntax is invalid?

```ceylon
class Cls() satisfies Bar {
    foo<A, B, C>() => nothing;
}
```

**Comment by gavinking** [comment]
Yes, you're totally right.

**Comment by gavinking** [comment]
(P.S. I wonder if that is something that is fixable in the language. I can't remember the reasoning why it's currently disallowed.)

**Comment by bjansen** [comment]
I noticed the assist should also be disabled if the `actual` declaration has a return type that is different from the `formal`'s (e.g. when I refine a Java interface and use the return type  `Foo?` instead of `Foo`).

**Comment by gavinking** [comment]
@bjansen I don't think you need to disable it in that case. Quick assists don't promise to not break code.

**Comment by bjansen** [comment]
Really? OK then.

**Comment by gavinking** [comment]
Fixed.

**Comment by bjansen** [comment]
thanks man
