### ISSUE TITLE
unified Find References

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#39]
Currently, we have four different flavors of Find Xxxxx, each with its own inconvenient accelerator key. This is a reasonable way to do things, based upon analysis of the use cases.

However, @bjansen points out that in IntelliJ, you get the same functionality just by classifying the results by kind in the search results list.

I think that's a better approach.

I propose the following categories:

1. subtypes
2. refinements
3. assignments
4. type usages
5. expression usages
6. imports
7. documentation strings

Probably, categories 1+2 could be merged and named "hierarchy", leaving us with six categories.

I guess this would be the top layer of the hierarchy of search results in the tree presentation.

WDYT?

**Comment by bjansen** [comment]
The current categories I have in IntelliJ are:

1. New instance creation
2. Import
3. Type Parameter
4. Method parameter
5. Extends/Implements

**Comment by bjansen** [comment]
FTR all the categories supported by IntelliJ are here: https://upsource.jetbrains.com/idea-ce/file/idea-ce-a05d35bf0f58985cdf09d5f59af16d159c2d4f1c/platform/usageView/src/com/intellij/usages/impl/rules/UsageType.java?nav=0:0:focused

**Comment by gavinking** [comment]
@bjansen I assume that list is for types?

> 1. New instance creation

This is roughly equivalent to what I've called "expression usages", I believe.

> 2. Import

Have that one.

> 3. Type Parameter

By which they actually mean "type argument", don't they?

> 4. Method parameter

By which they actually mean "type of a function parameter", don't they?

> 5. Extends/Implements

Roughly equivalent to what I've called "subtypes", I believe, except I'm assuming that it would be a recursive search for subtypes.


I actually don't want thousands of different categories, just a handful that reflect the typical use cases.

**Comment by bjansen** [comment]
* `if (is Foo foo)` is an expression usage, but not a new instance creation, right?
* type parameter == type argument, yes
* method parameter == reference is used as an argument to a function call, like `whatever(foo);`

**Comment by gavinking** [comment]
> * `if (is Foo foo)` is an expression usage, but not a new instance creation, right?

No. "`Foo`" here is a type expression not a value expression. Thus it's a "type usage".

On the other hand:

    value fun = Foo;

is an "expression usage". As is `Foo()`, of course.

> * method parameter == reference is used as an argument to a function call, like `whatever(foo);`

Oh gawd. IntelliJ doesn't know the difference between the words "parameter" and "argument"?!

Anyway, I don't see a good reason to have such fine categories. For example, why would `whatever(foo)`  show in one category and `let (x=foo) whatever(x)` show in a different category? That doesn't reflect any useful distinction.

**Comment by gavinking** [comment]
> On the other hand:
>
>    value fun = Foo;
>
> is an "expression usage". As is `Foo()`, of course.

Note that it's _of course_ correct that these belong in the same category. There is no difference between `value fun = Foo; fun();` and `Foo();`.

**Comment by bjansen** [comment]
I always mix up parameters and arguments too :(

**Comment by gavinking** [comment]
Well, I spent some time thinking about this and looking at what Eclipse's somewhat-inflexible search results view would actually let me implement. In the end I've come to the following conclusions:

1. I'm not going to make big changes to how all this currently works in Eclipse.
2. I *have* added the option to categorize search results by how the match occurs syntactically. The options are: "Declarations", "Assignments", "Uses in type expressions", "Uses in value expressions", "Imports", "References in documentation annotations", "References in Java code"
3. While I'm not going to remove "Find Subtypes" or "Find Refinements" from the Eclipse IDE, I'm not going to advocate that we implement them in the IntelliJ IDE. I'm considering removing "Find Assignments", but there's no pressure to do that right now.
4. I don't think this functionality belongs in ide-common after all.

I'm thus closing this issue.
