### ISSUE TITLE
Source-archive-based cross-project dependencies broken

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-common#52]
After the changes in `ceylon/ceylon` to support namespaces, the source archive of a required project is not found. The error is the following:
```
module.ceylon(4,11): cannot find module artifact referencedCeylonProject:1.0.0-.src.car
	- dependency tree: mainModule/1.0.0 -> referencedCeylonProject/1.0.0
```

**Comment by quintesse** [comment]
To me it seems as if `referencedCeylonProject:1.0.0` is passed as a module name somewhere with either a null or empty version string. (Artifact names are normally built up from `name + "-" + version + suffix`). The `.src.car` is really weird though.

**Comment by davidfestal** [comment]
In fact the ArtifactContext constructor call with 3 arguments didn't change, but the meaning of the three arguments did change since the addition of namespace at the first place. By the way I already fixed it but didn't push for now.

**Comment by davidfestal** [comment]
I've already fixed that some times ago
