### ISSUE TITLE
Suggest import namespaces

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon-ide-common#62]
We now have the concept of "import namespaces", eg:

    import maven:"junit-junit" "1.42";

It would be nice if we could complete the available namespaces, eg:

    import m<hit-suggest-here>

would show the namespaces starting with "m" as well as the list of modules starting with "m", eg:

    maven: - Namespace
    module1 - Module
    mymodule - Module

**Comment by quintesse** [comment]
The way to get the list of available namespaces is to get a reference to the `RepositoryManager` from the project context and then call .getRepositories() on it and then .getNamespace() on each of those.

This will give you the list of available namespaces for the repositories *configured* for the project (so if you didn't add the Aether repository the `maven:` prefix will not show up!).

**Comment by bjansen** [comment]
I suppose the `ceylon` namespace is implicit and we don't need to add it to the proposals?

**Comment by gavinking** [comment]
Right.

**Comment by bjansen** [comment]
Oops, namespaces shouldn't be suggested in module literals.
