### ISSUE TITLE
Completion not working on empty prefixes + inner classes

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-common#79]
In the following case:

```ceylon
import java.util { Map }
class Foo() satisfies List<Map.**cursor here**> {    
}
```

when I invoke completion I get a "list of every possible class in the universe" instead of a list of inner classes in `Map`. When the prefix is not empty (e.g. `E`), I get `Entry` as expected.

It seems to be working fine when calling completion outside of type parameters.

**Comment by gavinking** [comment]
This is probably more of a parser problem than an IDE problem per se.

**Comment by gavinking** [comment]
In fact, I get the same behavior here:

    List<Map.> list;

**Comment by bjansen** [comment]
Could be. It also happens here:

```
if (is List<Map.>)
```

**Comment by gavinking** [comment]
I know how to fix this, but I'm not very keen on messing with the parser this close to a release. So I suggest we do it for 1.3.1.

**Comment by gavinking** [comment]
@bjansen I have fixed this, though I really don't love the *way* I fixed it :-/
