### ISSUE TITLE
static methods of interfaces

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#87]
This code:

```ceylon
IntStream.range(0, 10).forEach((i) => print(i^2));
```

Results in this totally useless error:

```
Call to a static interface member is not allowed unless you set the -target flag to 8: --javac=-target=8
```

Grrrr!

**Comment by gavinking** [comment]
@davidfestal @bjansen this affects both Eclipse and IntelliJ.

**Comment by gavinking** [comment]
Temporary workaround, put:

```
[project]
javac=-target=8
```

In `ide-config`.

**Comment by gavinking** [comment]
> Temporary workaround

This workaround only works in Eclipse, not IntelliJ. :-(

**Comment by bjansen** [comment]
The official property is a compiler option in `config`:

```
[compiler.jvm]
javac=-target=8
```

**Comment by quintesse** [comment]
Shouldn't this be:

```
[compiler]
target=8
```

?

**Comment by gavinking** [comment]
Is there _any way_ to figure out which "sections" all these various settings belong to?

Frankly I don't think that's documented anywhere.

**Comment by bjansen** [comment]
Look at the constants in https://github.com/ceylon/ceylon/blob/master/common/src/com/redhat/ceylon/common/config/DefaultToolOptions.java

**Comment by gavinking** [comment]
@quintesse no, that doesn't work.

**Comment by gavinking** [comment]
@bjansen nope, that doesn't work either.

**Comment by bjansen** [comment]
Sure it works, I just tested it.

**Comment by gavinking** [comment]
OK, so what works is:

1. In Eclipse, use `ide-config`:
    
        [project]
        javac=-target=8
2. In IntelliJ, use `config`
    
        [compiler.jvm]
        javac=-target=8

**Comment by gavinking** [comment]
So it's not even a consistent behavior across the two IDEs.

**Comment by bjansen** [comment]
@davidfestal started something for Eclipse, then @quintesse introduced another property that is officially supported by the compiler, so I used that one. We should change Eclipse to use the one in `config`.

**Comment by gavinking** [comment]
Well, no, fuck that, things are suppose to _just work_.

Enough with these ridiculous command line options and fucking with undocumented config file formats!

Seriously.

**Comment by gavinking** [comment]
This is the kind of software I *hate*.

**Comment by quintesse** [comment]
The options *and* the format are documented: https://ceylon-lang.org/documentation/1.3/reference/tool/config/

But the `target` option is new so of course it's not there yet.

And in the IDEs it should just be a configuration option in a dialog somewhere, you should not have to dally with config files obviously.

**Comment by bjansen** [comment]
Stef and I just realized that `JavaCompilerOptions` is missing the `target` option, so once this is added we shouldn't need to explicitly set a target version in the config.

**Comment by gavinking** [comment]
> The options and the format are documented

OK, fine, I'm wrong. They are mostly documented. Just not this one.

**Comment by bjansen** [comment]
This is fixed in IntelliJ, you don't need to change the config anymore. BTW there's already a UI to change the `javac` options:

<img width="938" alt="capture d ecran 2016-10-21 a 12 49 34" src="https://cloud.githubusercontent.com/assets/281528/19596023/dc8a68d8-978c-11e6-95e9-f9f2fd51a425.png">

I guess for Eclipse we need to revert part of https://github.com/ceylon/ceylon-ide-eclipse/issues/1787 and use `DefaultToolsOptions.getCompilerTargetVersion()` instead.

**Comment by gavinking** [comment]
@bjansen any chance you could make the change, since @davidfestal is on vacation?

**Comment by bjansen** [comment]
pffffffff

**Comment by bjansen** [comment]
Done for Eclipse.

**Comment by gavinking** [comment]
@bjansen thanks.
