### ISSUE TITLE
clean nested import statements

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-common#99]
'Clean Imports' currently ignores nested `import` statements.

**Comment by gavinking** [comment]
Also, autocompletion adds dupe imports for things already imported by a nested import,

**Comment by gavinking** [comment]
I've done a bunch of work to improve IDE support for nested imports. Seems to be working much nicer now.

**Comment by bjansen** [comment]
Does it mean the IDE is now capable of *adding* new nested imports? That would be convenient for the quick assist that replaces `javaString` with `Types.nativeString` for example.

**Comment by gavinking** [comment]
That's not what I mean by nested. I mean when the import statement is nested inside a declaration.

**Comment by bjansen** [comment]
Oh, ok :)
